### ISSUE TITLE
css/scss theme

### ISSUE THREAD

**Issue by gbreeze** [aurelia/vscode-extension#34]
Hi, I like the html theme with the aurelia highlights a lot, but the css/scss theme looks compared to the native theme boring. Would be good if we can use the aurelia theme for html only.

Best regards,
George

**Comment by eriklieben** [comment]
Thanks for the feedback!

In version 1.9.0 of vscode some changed where applied to the themes.
Published a quick fix yesterday to resolve them, which looked at first if everything worked again, but seems like there is more to it.

Will look into it.

**Comment by eriklieben** [comment]
Will release a new version later on today that contains this fix.

**Comment by eriklieben** [comment]
Fixed in release 0.2.3

**Comment by gbreeze** [comment]
HI, on the aurelia light themes everything is fine, but on the black themes there is still the same css/scss highlighting issue. 

aurelia black theme:
![image](https://cloud.githubusercontent.com/assets/1906169/22854893/d2c61b60-f076-11e6-8b58-f9f2c5afe4f2.png)

native theme:
![image](https://cloud.githubusercontent.com/assets/1906169/22854897/0cf4c278-f077-11e6-8238-a0ec1e55bfcb.png)

**Comment by gbreeze** [comment]
Thanks, works now fine to ;-). 👍
